import{useEffect,useMemo,useRef,useState}from"react";
import type{KeyboardEvent,MouseEvent}from"react";
import*as XLSX from"xlsx";
import{cellKey,displayCell,formatNumber,parseCellKey,parseCsv,shiftFormulaReferences,toDelimited,type CellStyle,type NumberFormat,type Workbook}from"@kz-nexa/shared";
type User={id:string;email:string;name:string;role:string};type Auth={token:string;user:User};type Point={row:number;col:number};
const API="https://kz-nexa.onrender.com",ROWS=200,COLS=50;
const readAuth=():Auth|null=>{try{const x=JSON.parse(localStorage.getItem("nexa:auth")||"null");return x?.token&&x?.user?.id?x:null}catch{return null}};
const fresh=(ownerId:string):Workbook=>{const now=new Date().toISOString(),id=crypto.randomUUID();return{ownerId,name:"Nova planilha",schemaVersion:4,sheets:[{id,name:"Planilha 1",cells:{},columnWidths:{},rowHeights:{},frozenRows:0,frozenColumns:0,hiddenRows:{},hiddenColumns:{},mergedRanges:[]}],activeSheetId:id,createdAt:now,updatedAt:now}};
const clone=<T,>(x:T):T=>structuredClone(x);
const point=(k:string)=>parseCellKey(k);
const keysBetween=(a:Point,b:Point)=>{const out:string[]=[];for(let r=Math.min(a.row,b.row);r<=Math.max(a.row,b.row);r++)for(let c=Math.min(a.col,b.col);c<=Math.max(a.col,b.col);c++)out.push(cellKey(r,c));return out};
const range=(a:string,b:string)=>a===b?a+":"+b:a+":"+b;
function mergeOwner(sheet:any,key:string){for(const r of sheet.mergedRanges||[]){const [a,b]=r.split(":");if(keysBetween(point(a),point(b)).includes(key))return a}return null}
function sumCols(sheet:any,from:number,to:number){let n=0;for(let c=from;c<=to;c++)n+=sheet.columnWidths[String(c)]||110;return n}
function sumRows(sheet:any,from:number,to:number){let n=0;for(let r=from;r<=to;r++)n+=sheet.rowHeights[String(r)]||28;return n}
function csvEsc(v:string){return /[",\n\r]/.test(v)?'"'+v.replaceAll('"','""')+'"':v}
export function App(){const[auth,setAuth]=useState<Auth|null>(readAuth),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[loginError,setLoginError]=useState(""),[loginBusy,setLoginBusy]=useState(false);
if(!auth)return <Login email={email} password={password} setEmail={setEmail} setPassword={setPassword} error={loginError} busy={loginBusy} submit={async()=>{setLoginBusy(true);setLoginError("");try{const r=await fetch(API+"/v1/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,password})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||"Não foi possível entrar.");localStorage.setItem("nexa:auth",JSON.stringify(d));setAuth(d);setPassword("")}catch(e){setLoginError(e instanceof Error?e.message:"Falha no login")}finally{setLoginBusy(false)}}}/>;return <Spreadsheet auth={auth} logout={()=>{localStorage.removeItem("nexa:auth");setAuth(null)}}/>}
function Login(p:{email:string;password:string;setEmail:(v:string)=>void;setPassword:(v:string)=>void;error:string;busy:boolean;submit:()=>Promise<void>}){return <div className="login"><div className="loginCard"><div className="loginLogo">N</div><h1>Korczak Nexa</h1><p>Entre com sua conta Korczak para continuar.</p><form onSubmit={e=>{e.preventDefault();void p.submit()}}><label>Email<input type="email" value={p.email} onChange={e=>p.setEmail(e.target.value)} autoComplete="username" required/></label><label>Senha<input type="password" value={p.password} onChange={e=>p.setPassword(e.target.value)} autoComplete="current-password" required/></label>{p.error&&<div className="loginError">{p.error}</div>}<button disabled={p.busy}>{p.busy?"Entrando...":"Entrar"}</button></form></div></div>}
function Spreadsheet({auth,logout}:{auth:Auth;logout:()=>void}){const[w,setW]=useState<Workbook>(()=>fresh(auth.user.id)),[selection,setSelection]=useState({start:"A1",end:"A1"}),[editing,setEditing]=useState(false),[editValue,setEditValue]=useState(""),[formula,setFormula]=useState(""),[undo,setUndo]=useState<Workbook[]>([]),[redo,setRedo]=useState<Workbook[]>([]),[status,setStatus]=useState("carregando"),[zoom,setZoom]=useState(100),[loaded,setLoaded]=useState(false),[documents,setDocuments]=useState<Workbook[]>([]),[showDocs,setShowDocs]=useState(false),[fileType,setFileType]=useState("xlsx"),drag=useRef(false),editRef=useRef<HTMLInputElement>(null);
const sheet=w.sheets.find(s=>s.id===w.activeSheetId)||w.sheets[0],active=selection.start,selectedKeys=useMemo(()=>keysBetween(point(selection.start),point(selection.end)),[selection]);
const request=async(path:string,init:RequestInit={})=>{const headers=new Headers(init.headers);headers.set("Authorization","Bearer "+auth.token);if(init.body&&!headers.has("content-type"))headers.set("content-type","application/json");const r=await fetch(API+path,{...init,headers});if(r.status===401){logout();throw Error("Sessão expirada.")}return r};
useEffect(()=>{const v=sheet?.cells[active]?.input||"";setFormula(v);if(!editing)setEditValue(v)},[active,sheet,editing]);
useEffect(()=>{if(editing)editRef.current?.focus()},[editing]);
useEffect(()=>{(async()=>{try{const r=await request("/v1/workbooks");if(!r.ok)throw Error();const list=await r.json() as Workbook[];setDocuments(list);if(list[0])setW(list[0]);setStatus(list[0]?"carregado":"novo")}catch{setStatus("offline")}finally{setLoaded(true)}})()},[]);
const value=(sName:string|undefined,key:string)=>{const s=w.sheets.find(x=>x.name===sName||x.id===sName);return s?.cells[key]?.input||""};
const rendered=(key:string)=>{const c=sheet.cells[key];if(!c)return"";const f=c.style?.numberFormat||"general",raw=c.input;if(!raw.startsWith("=")){const n=Number(raw.replace(",","."));return f!=="general"&&raw.trim()!==""&&Number.isFinite(n)?formatNumber(n,f):raw}return displayCell(raw,(sn,k)=>value(sn||sheet.name,k),sheet.name,v=>typeof v==="number"?formatNumber(v,f):String(v))};
const change=(fn:(x:Workbook)=>void)=>{setUndo(a=>[...a.slice(-99),clone(w)]);setRedo([]);const x=clone(w);fn(x);x.updatedAt=new Date().toISOString();setW(x);setStatus("não salvo")};
const replaceSelection=(input:string[][])=>change(x=>{const s=x.sheets.find(a=>a.id===x.activeSheetId)!;const p=point(selection.start);input.forEach((row,r)=>row.forEach((v,c)=>{const k=cellKey(p.row+r,p.col+c);if(v==="")delete s.cells[k];else s.cells[k]={...(s.cells[k]||{input:""}),input:v}}))});
const commitEdit=()=>{if(!editing)return;replaceSelection([[editValue]]);setFormula(editValue);setEditing(false)};
const beginEdit=(v:string)=>{setEditValue(v);setEditing(true)};
const style=(key:keyof CellStyle,val:unknown)=>change(x=>{const s=x.sheets.find(a=>a.id===x.activeSheetId)!;for(const k of selectedKeys){const c=s.cells[k]||{input:""};s.cells[k]={...c,style:{...c.style,[key]:val}}}});
const toggle=(key:keyof CellStyle)=>style(key,!sheet.cells[active]?.style?.[key]);
const save=async()=>{setStatus("salvando");try{const has=Boolean(w._id),r=await request(has?"/v1/workbooks/"+w._id:"/v1/workbooks",{method:has?"PUT":"POST",body:JSON.stringify(w)});if(!r.ok)throw Error();const saved=await r.json() as Workbook;setW(saved);setDocuments(a=>[saved,...a.filter(x=>x._id!==saved._id)]);setStatus("salvo")}catch{setStatus("offline")}};
const newWorkbook=()=>{setW(fresh(auth.user.id));setSelection({start:"A1",end:"A1"});setUndo([]);setRedo([]);setStatus("novo")};
const openDoc=(d:Workbook)=>{setW(d);setSelection({start:"A1",end:"A1"});setShowDocs(false);setStatus("carregado")};
const addSheet=()=>change(x=>{const id=crypto.randomUUID();x.sheets.push({id,name:"Planilha "+(x.sheets.length+1),cells:{},columnWidths:{},rowHeights:{},frozenRows:0,frozenColumns:0,hiddenRows:{},hiddenColumns:{},mergedRanges:[]});x.activeSheetId=id});
const undoIt=()=>{const p=undo.at(-1);if(!p)return;setRedo(a=>[clone(w),...a]);setUndo(a=>a.slice(0,-1));setW(p)},redoIt=()=>{const n=redo[0];if(!n)return;setUndo(a=>[...a,clone(w)]);setRedo(a=>a.slice(1));setW(n)};
const copy=async()=>{const a=point(selection.start),b=point(selection.end),rows=b.row-a.row+1,cols=b.col-a.col+1,text=Array.from({length:rows},(_,r)=>Array.from({length:cols},(_,c)=>sheet.cells[cellKey(a.row+r,a.col+c)]?.input||"").join("\t")).join("\n");try{await navigator.clipboard.writeText(text);setStatus("copiado")}catch{setStatus("clipboard indisponível")}};
const paste=async()=>{try{replaceSelection((await navigator.clipboard.readText()).split(/\r?\n/).map(r=>r.split("\t")));setStatus("colado")}catch{setStatus("não foi possível colar")}};
const fillSelection=()=>change(x=>{const s=x.sheets.find(a=>a.id===x.activeSheetId)!;const a=point(selection.start),b=point(selection.end),height=b.row-a.row+1,width=b.col-a.col+1;const copy=(src:string,dr:number,dc:number)=>src.startsWith("=")?shiftFormulaReferences(src,dr,dc):src;if(height>1){for(let r=1;r<height;r++)for(let c=0;c<width;c++){const k1=cellKey(a.row,a.col+c),k2=cellKey(a.row+1,a.col+c),target=cellKey(a.row+r,a.col+c),v1=s.cells[k1]?.input||"",v2=s.cells[k2]?.input||"";let v=copy(v1,r,0);const n1=Number(v1.replace(",",".")),n2=Number(v2.replace(",","."));if(r>=2&&Number.isFinite(n1)&&Number.isFinite(n2)&&!v1.startsWith("=")&&!v2.startsWith("="))v=String(n1+(n2-n1)*r).replace(".",",");else if(r>=2&&v1!==v2&&v1.startsWith("="))v=copy(v1,r,0);s.cells[target]={...(s.cells[target]||{input:""}),input:v}}}else if(width>1){for(let c=1;c<width;c++){const k1=cellKey(a.row,a.col),k2=cellKey(a.row,a.col+1),target=cellKey(a.row,a.col+c),v1=s.cells[k1]?.input||"",v2=s.cells[k2]?.input||"",n1=Number(v1.replace(",",".")),n2=Number(v2.replace(",","."));let v=copy(v1,0,c);if(c>=2&&Number.isFinite(n1)&&Number.isFinite(n2)&&!v1.startsWith("=")&&!v2.startsWith("="))v=String(n1+(n2-n1)*c).replace(".",",");s.cells[target]={...(s.cells[target]||{input:""}),input:v}}}});
const merge=()=>change(x=>{const s=x.sheets.find(a=>a.id===x.activeSheetId)!;const a=point(selection.start),b=point(selection.end);if(a.row===b.row&&a.col===b.col)return;const r=range(cellKey(a.row,a.col),cellKey(b.row,b.col));s.mergedRanges=Array.from(new Set([...(s.mergedRanges||[]),r]));for(const k of selectedKeys)if(k!==cellKey(a.row,a.col))delete s.cells[k]});
const unmerge=()=>change(x=>{const s=x.sheets.find(a=>a.id===x.activeSheetId)!;s.mergedRanges=(s.mergedRanges||[]).filter(r=>!selectedKeys.includes(r.split(":")[0]))});
const freezeRows=()=>change(x=>{const s=x.sheets.find(a=>a.id===x.activeSheetId)!;s.frozenRows=point(selection.start).row+1});
const freezeCols=()=>change(x=>{const s=x.sheets.find(a=>a.id===x.activeSheetId)!;s.frozenColumns=point(selection.start).col+1});
const unfreeze=()=>change(x=>{const s=x.sheets.find(a=>a.id===x.activeSheetId)!;s.frozenRows=0;s.frozenColumns=0});
const exportFile=()=>{const ext=fileType.toLowerCase();if(ext==="csv"||ext==="tsv"){const rows=Object.keys(sheet.cells);const maxR=rows.length?Math.max(...rows.map(k=>point(k).row)):0,maxC=rows.length?Math.max(...rows.map(k=>point(k).col)):0;const data=Array.from({length:maxR+1},(_,r)=>Array.from({length:maxC+1},(_,c)=>sheet.cells[cellKey(r,c)]?.input||""));const text=toDelimited(data,ext==="tsv"?"\t":",");const blob=new Blob([text],{type:"text/plain;charset=utf-8"});downloadBlob(blob,w.name+"."+ext);return}const wb=XLSX.utils.book_new();for(const s of w.sheets){const used=Object.keys(s.cells),maxR=used.length?Math.max(...used.map(k=>point(k).row)):0,maxC=used.length?Math.max(...used.map(k=>point(k).col)):0,data=Array.from({length:maxR+1},(_,r)=>Array.from({length:maxC+1},(_,c)=>s.cells[cellKey(r,c)]?.input||""));XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(data),s.name.slice(0,31)||"Planilha")}const out=XLSX.write(wb,{bookType:ext==="ods"?"ods":"xlsx",type:"array"});downloadBlob(new Blob([out]),w.name+"."+ext)};
const downloadBlob=(blob:Blob,name:string)=>{const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0)};
const importFile=async(file:File)=>{try{const ext=file.name.toLowerCase().split(".").pop();if(ext==="csv"||ext==="tsv"){const text=await file.text();replaceSelection(parseCsv(ext==="tsv"?text.replaceAll("\t",","):text));setStatus("importado");return}const wb=XLSX.read(await file.arrayBuffer(),{type:"array"}),ws=wb.Sheets[wb.SheetNames[0]],data=XLSX.utils.sheet_to_json<string[]>(ws,{header:1,raw:false});replaceSelection(data.map(r=>r.map(v=>String(v??""))));setStatus("importado")}catch{setStatus("erro na importação")}};
const move=(dr:number,dc:number,extend:boolean)=>{const p=point(extend?selection.end:active),n={row:Math.max(0,p.row+dr),col:Math.max(0,p.col+dc)},k=cellKey(n.row,n.col);setSelection(extend?{...selection,end:k}:{start:k,end:k})};
const onKey=(e:KeyboardEvent)=>{if(editing){if(e.key==="Enter"){e.preventDefault();commitEdit();move(e.shiftKey?-1:1,0,false)}else if(e.key==="Escape"){e.preventDefault();setEditing(false);setEditValue(sheet.cells[active]?.input||"")}return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"){e.preventDefault();e.shiftKey?redoIt():undoIt();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="y"){e.preventDefault();redoIt();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="c"){e.preventDefault();void copy();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="v"){e.preventDefault();void paste();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="b"){e.preventDefault();toggle("bold");return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="i"){e.preventDefault();toggle("italic");return}if(e.key==="Delete"||e.key==="Backspace"){e.preventDefault();replaceSelection([[""]]);return}if(e.key==="Enter"||e.key==="F2"){e.preventDefault();beginEdit(sheet.cells[active]?.input||"");return}if(e.key==="Tab"){e.preventDefault();move(0,e.shiftKey?-1:1,false);return}if(e.key==="ArrowUp"){e.preventDefault();move(-1,0,e.shiftKey);return}if(e.key==="ArrowDown"){e.preventDefault();move(1,0,e.shiftKey);return}if(e.key==="ArrowLeft"){e.preventDefault();move(0,-1,e.shiftKey);return}if(e.key==="ArrowRight"){e.preventDefault();move(0,1,e.shiftKey);return}if(e.key.length===1&&!e.ctrlKey&&!e.metaKey&&!e.altKey)beginEdit((sheet.cells[active]?.input||"")+e.key)};
const resize=(axis:"c"|"r",index:number)=>{const size=prompt(axis==="c"?"Largura da coluna (px)":"Altura da linha (px)",axis==="c"?String(sheet.columnWidths[String(index)]||110):String(sheet.rowHeights[String(index)]||28));if(size&&Number(size)>15)change(x=>{const s=x.sheets.find(a=>a.id===x.activeSheetId)!;(axis==="c"?s.columnWidths:s.rowHeights)[String(index)]=Number(size)})};
if(!loaded)return <div className="loading">Korczak Nexa<br/><small>Carregando...</small></div>;
const selected=(k:string)=>selectedKeys.includes(k);
return <div className="nexa" tabIndex={0} onKeyDown={onKey}><header><div className="brand"><b>N</b><strong>Korczak Nexa</strong><input value={w.name} onChange={e=>{setW({...w,name:e.target.value});setStatus("não salvo")}}/></div><div className="actions"><span>{auth.user.name}</span><button onClick={newWorkbook}>Novo</button><button onClick={()=>setShowDocs(true)}>Abrir</button><button onClick={undoIt} disabled={!undo.length}>↶</button><button onClick={redoIt} disabled={!redo.length}>↷</button><button onClick={()=>void save()}>Salvar</button><label className="import">Importar<input type="file" accept=".csv,.tsv,.xlsx,.ods,text/csv" onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f);e.currentTarget.value=""}}/></label><select value={fileType} onChange={e=>setFileType(e.target.value)}><option value="xlsx">XLSX</option><option value="ods">ODS</option><option value="csv">CSV</option><option value="tsv">TSV</option></select><button onClick={exportFile}>Exportar</button><button onClick={logout}>Sair</button><span>{status}</span></div></header>
<nav><button onClick={()=>setShowDocs(true)}>Arquivo</button><button>Início</button><button>Inserir</button><button>Dados</button><button>Exibir</button><button onClick={()=>toggle("bold")} className={sheet.cells[active]?.style?.bold?"on":""}><b>B</b></button><button onClick={()=>toggle("italic")} className={sheet.cells[active]?.style?.italic?"on":""}><i>I</i></button><button onClick={()=>toggle("underline")} className={sheet.cells[active]?.style?.underline?"on":""}><u>U</u></button><button onClick={()=>toggle("strike")} className={sheet.cells[active]?.style?.strike?"on":""}><s>S</s></button><button onClick={()=>style("align","left")}>⇤</button><button onClick={()=>style("align","center")}>≡</button><button onClick={()=>style("align","right")}>⇥</button><select value={sheet.cells[active]?.style?.numberFormat||"general"} onChange={e=>style("numberFormat",e.target.value as NumberFormat)}><option value="general">Geral</option><option value="number">Número</option><option value="currency">Moeda</option><option value="percent">Porcentagem</option><option value="date">Data</option><option value="time">Hora</option></select><button onClick={fillSelection}>Preencher</button><button onClick={merge}>Mesclar</button><button onClick={unmerge}>Desmesclar</button><button onClick={freezeRows}>Congelar linhas</button><button onClick={freezeCols}>Congelar colunas</button><button onClick={unfreeze}>Descongelar</button><button onClick={addSheet}>＋ Planilha</button><label>Zoom <input type="range" min="50" max="200" value={zoom} onChange={e=>setZoom(+e.target.value)}/>{zoom}%</label></nav>
<div className="formula"><strong>{selection.start}{selection.end!==selection.start?" : "+selection.end:""}</strong><input ref={editRef} value={editing?editValue:formula} onChange={e=>{if(editing)setEditValue(e.target.value);else{setFormula(e.target.value);setEditValue(e.target.value)}}} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();if(editing)commitEdit();else{setEditValue(formula);setEditing(true)}}}} placeholder="Valor ou fórmula"/><button onClick={()=>{if(editing)commitEdit();else{setEditValue(formula);setEditing(true)}}}>✓</button></div>
<div className="viewport"><div className="grid" style={{zoom:zoom/100}}><div className="corner"/>{Array.from({length:COLS},(_,c)=><div className="head" key={"c"+c} style={c<sheet.frozenColumns?{left:48+sumCols(sheet,0,c-1),zIndex:5}:undefined} onDoubleClick={()=>resize("c",c)}>{String.fromCharCode(65+c)}</div>)}{Array.from({length:ROWS},(_,r)=><div className="gridrow" key={"row"+r}><div className="row" style={r<sheet.frozenRows?{top:28+sumRows(sheet,0,r-1),zIndex:4}:undefined} onDoubleClick={()=>resize("r",r)}>{r+1}</div>{Array.from({length:COLS},(_,c)=>{const k=cellKey(r,c),st=sheet.cells[k]?.style||{},owner=mergeOwner(sheet,k),isOwner=owner===k,merged=owner&&isOwner?owner:null;let width=sheet.columnWidths[String(c)]||110,height=sheet.rowHeights[String(r)]||28;if(merged){const [a,b]=merged.split(":");const q=point(b);width=sumCols(sheet,c,q.col);height=sumRows(sheet,r,q.row)}if(owner&&!isOwner)return null;const stickyTop=r<sheet.frozenRows?28+sumRows(sheet,0,r-1):undefined,stickyLeft=c<sheet.frozenColumns?48+sumCols(sheet,0,c-1):undefined;return <div className={"cell "+(selected(k)?"selected ":"")} style={{width,height,fontWeight:st.bold?"700":"400",fontStyle:st.italic?"italic":"normal",textDecoration:[st.underline?"underline":"",st.strike?"line-through":""].filter(Boolean).join(" "),textAlign:st.align||"left",whiteSpace:st.wrap?"normal":"nowrap",position:stickyTop!==undefined||stickyLeft!==undefined?"sticky":undefined,top:stickyTop,left:stickyLeft,zIndex:stickyTop!==undefined&&stickyLeft!==undefined?6:stickyTop!==undefined||stickyLeft!==undefined?4:1}} key={k} onMouseDown={(e:MouseEvent)=>{drag.current=true;setSelection({start:k,end:k});e.preventDefault()}} onMouseEnter={()=>drag.current&&setSelection(s=>({...s,end:k}))} onMouseUp={()=>{drag.current=false}} onDoubleClick={()=>beginEdit(sheet.cells[k]?.input||"")}>{editing&&active===k?<input className="cellEditor" autoFocus value={editValue} onChange={e=>setEditValue(e.target.value)} onKeyDown={onKey} onBlur={commitEdit}/>:rendered(k)}</div>})}</div>)}</div></div>
<footer>{w.sheets.map(s=><button className={s.id===sheet.id?"active":""} key={s.id} onClick={()=>setW({...w,activeSheetId:s.id})}>{s.name}</button>)}</footer>
{showDocs&&<div className="modal"><div className="dialog"><div className="dialogHead"><strong>Planilhas</strong><button onClick={()=>setShowDocs(false)}>×</button></div><button className="newDoc" onClick={()=>{newWorkbook();setShowDocs(false)}}>＋ Nova planilha</button>{documents.length?documents.map(d=><button className="doc" key={d._id||d.name} onClick={()=>openDoc(d)}><strong>{d.name}</strong><small>{new Date(d.updatedAt).toLocaleString("pt-BR")}</small></button>):<p>Nenhuma planilha salva ainda.</p>}</div></div>}</div>}
