import{useEffect,useMemo,useRef,useState}from"react";import type{ChangeEvent,KeyboardEvent,MouseEvent}from"react";import{cellKey,displayCell,formatNumber,parseCellKey,parseCsv,type CellStyle,type NumberFormat,type Workbook}from"@kz-nexa/shared";
const API="https://kz-nexa.onrender.com";const ROWS=100,COLS=26;type Point={row:number;col:number};
const fresh=():Workbook=>{const now=new Date().toISOString(),sheetId=crypto.randomUUID();return{ownerId:localStorage.getItem("nexa:userId")||"anonymous",name:"Nova planilha",schemaVersion:3,sheets:[{id:sheetId,name:"Planilha 1",cells:{},columnWidths:{},rowHeights:{},frozenRows:0,frozenColumns:0}],activeSheetId:sheetId,createdAt:now,updatedAt:now}};
function clone<T>(x:T):T{return structuredClone(x)}function point(k:string):Point{return parseCellKey(k)}function keysBetween(a:Point,b:Point){const out:string[]=[];for(let r=Math.min(a.row,b.row);r<=Math.max(a.row,b.row);r++)for(let c=Math.min(a.col,b.col);c<=Math.max(a.col,b.col);c++)out.push(cellKey(r,c));return out}function csvEsc(v:string){return /[",\n\r]/.test(v)?'"'+v.replaceAll('"','""')+'"':v}
export function App(){const[w,setW]=useState<Workbook>(fresh),[selection,setSelection]=useState<{start:string;end:string}>({start:"A1",end:"A1"}),[editing,setEditing]=useState(false),[editValue,setEditValue]=useState(""),[formula,setFormula]=useState(""),[undo,setUndo]=useState<Workbook[]>([]),[redo,setRedo]=useState<Workbook[]>([]),[status,setStatus]=useState("carregando"),[zoom,setZoom]=useState(100),[loaded,setLoaded]=useState(false),[documents,setDocuments]=useState<Workbook[]>([]),[showDocs,setShowDocs]=useState(false),drag=useRef(false),editRef=useRef<HTMLInputElement>(null);
const sheet=w.sheets.find(s=>s.id===w.activeSheetId)||w.sheets[0];const active=selection.start;const selectedKeys=useMemo(()=>keysBetween(point(selection.start),point(selection.end)),[selection]);
useEffect(()=>{const v=sheet?.cells[active]?.input||"";setFormula(v);if(!editing)setEditValue(v)},[active,sheet,editing]);
useEffect(()=>{if(editing)editRef.current?.focus()},[editing]);
useEffect(()=>{(async()=>{try{const owner=encodeURIComponent(w.ownerId);const r=await fetch(API+"/v1/workbooks?ownerId="+owner);if(!r.ok)throw new Error();const list=await r.json() as Workbook[];setDocuments(list);if(list[0])setW(list[0]);setStatus(list[0]?"carregado":"novo")}catch{setStatus("offline")}finally{setLoaded(true)}})()},[]);
const value=(sName:string|undefined,key:string)=>{const s=w.sheets.find(x=>x.name===sName||x.id===sName);return s?.cells[key]?.input||""};
const rendered=(key:string)=>{const c=sheet.cells[key];if(!c)return"";const f=c.style?.numberFormat||"general";const raw=c.input;if(!raw.startsWith("=")){const n=Number(raw.replace(",","."));return f!=="general"&&raw.trim()!==""&&Number.isFinite(n)?formatNumber(n,f):raw}return displayCell(raw,(sn,k)=>value(sn||sheet.name,k),sheet.name,v=>typeof v==="number"?formatNumber(v,f):String(v))};
const change=(fn:(x:Workbook)=>void)=>{setUndo(a=>[...a.slice(-99),clone(w)]);setRedo([]);const x=clone(w);fn(x);x.updatedAt=new Date().toISOString();setW(x);setStatus("não salvo")};
const replaceSelection=(input:string[][])=>change(x=>{const s=x.sheets.find(a=>a.id===x.activeSheetId)!;const p=point(selection.start);input.forEach((row,r)=>row.forEach((v,c)=>{const k=cellKey(p.row+r,p.col+c);if(v==="")delete s.cells[k];else s.cells[k]={...(s.cells[k]||{}),input:v}}))});
const commitEdit=()=>{if(!editing)return;replaceSelection([[editValue]]);setEditing(false)};
const beginEdit=(value:string)=>{setEditValue(value);setEditing(true)};
const style=(key:keyof CellStyle,val:unknown)=>change(x=>{const s=x.sheets.find(a=>a.id===x.activeSheetId)!;for(const k of selectedKeys){const c=s.cells[k]||{input:""};s.cells[k]={...c,style:{...c.style,[key]:val}}}});
const toggle=(key:keyof CellStyle)=>style(key,!sheet.cells[active]?.style?.[key]);
const save=async()=>{setStatus("salvando");try{const has=Boolean(w._id);const r=await fetch(has?API+"/v1/workbooks/"+w._id:API+"/v1/workbooks",{method:has?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(w)});if(!r.ok)throw new Error();const saved=await r.json() as Workbook;setW(saved);setDocuments(a=>[saved,...a.filter(x=>x._id!==saved._id)]);setStatus("salvo")}catch{setStatus("offline")}};
const newWorkbook=()=>{setW(fresh());setSelection({start:"A1",end:"A1"});setUndo([]);setRedo([]);setStatus("novo")};
const openDoc=(d:Workbook)=>{setW(d);setSelection({start:"A1",end:"A1"});setShowDocs(false);setStatus("carregado")};
const addSheet=()=>change(x=>{const id=crypto.randomUUID();x.sheets.push({id,name:"Planilha "+(x.sheets.length+1),cells:{},columnWidths:{},rowHeights:{},frozenRows:0,frozenColumns:0});x.activeSheetId=id});
const undoIt=()=>{const p=undo.at(-1);if(!p)return;setRedo(a=>[clone(w),...a]);setUndo(a=>a.slice(0,-1));setW(p);setStatus("alterado")};const redoIt=()=>{const n=redo[0];if(!n)return;setUndo(a=>[...a,clone(w)]);setRedo(a=>a.slice(1));setW(n);setStatus("alterado")};
const copy=async()=>{const rows=Math.max(...selectedKeys.map(k=>point(k).row))-Math.min(...selectedKeys.map(k=>point(k).row))+1,cols=Math.max(...selectedKeys.map(k=>point(k).col))-Math.min(...selectedKeys.map(k=>point(k).col))+1;const p=point(selection.start);const text=Array.from({length:rows},(_,r)=>Array.from({length:cols},(_,c)=>sheet.cells[cellKey(p.row+r,p.col+c)]?.input||"").join("\t")).join("\n");try{await navigator.clipboard.writeText(text);setStatus("copiado")}catch{setStatus("clipboard indisponível")}};
const paste=async()=>{try{const raw=await navigator.clipboard.readText();replaceSelection(raw.split(/\r?\n/).map(r=>r.split("\t")));setStatus("colado")}catch{setStatus("não foi possível colar")}};
const exportCsv=()=>{const used=Object.keys(sheet.cells);const maxR=used.length?Math.max(...used.map(k=>point(k).row)):0,maxC=used.length?Math.max(...used.map(k=>point(k).col)):0;const csv=Array.from({length:maxR+1},(_,r)=>Array.from({length:maxC+1},(_,c)=>csvEsc(sheet.cells[cellKey(r,c)]?.input||"")).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download=w.name+".csv";a.click();URL.revokeObjectURL(a.href)};
const importCsv=(file:File)=>{const rd=new FileReader();rd.onload=()=>replaceSelection(parseCsv(String(rd.result)) );rd.readAsText(file)};
const move=(dr:number,dc:number,extend:boolean)=>{const p=point(extend?selection.end:active),n={row:Math.max(0,p.row+dr),col:Math.max(0,p.col+dc)},k=cellKey(n.row,n.col);setSelection(extend?{...selection,end:k}:{start:k,end:k})};
const onKey=(e:KeyboardEvent)=>{if(editing){if(e.key==="Enter"){e.preventDefault();commitEdit();move(e.shiftKey?-1:1,0,false)}else if(e.key==="Escape"){e.preventDefault();setEditing(false);setEditValue(sheet.cells[active]?.input||"")}return}
if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"){e.preventDefault();e.shiftKey?redoIt():undoIt();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="y"){e.preventDefault();redoIt();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="c"){e.preventDefault();void copy();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="v"){e.preventDefault();void paste();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="b"){e.preventDefault();toggle("bold");return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="i"){e.preventDefault();toggle("italic");return}
if(e.key==="Delete"||e.key==="Backspace"){e.preventDefault();replaceSelection([[""]]);return}if(e.key==="Enter"){e.preventDefault();beginEdit(sheet.cells[active]?.input||"");return}if(e.key==="F2"){e.preventDefault();beginEdit(sheet.cells[active]?.input||"");return}if(e.key==="Tab"){e.preventDefault();move(0,e.shiftKey?-1:1,false);return}if(e.key==="ArrowUp"){e.preventDefault();move(-1,0,e.shiftKey);return}if(e.key==="ArrowDown"){e.preventDefault();move(1,0,e.shiftKey);return}if(e.key==="ArrowLeft"){e.preventDefault();move(0,-1,e.shiftKey);return}if(e.key==="ArrowRight"){e.preventDefault();move(0,1,e.shiftKey);return}if(e.key.length===1&&!e.ctrlKey&&!e.metaKey&&!e.altKey)beginEdit(sheet.cells[active]?.input?sheet.cells[active].input+e.key:e.key)};
const resize=(axis:"c"|"r",index:number)=>{const size=prompt(axis==="c"?"Largura da coluna (px)":"Altura da linha (px)",axis==="c"?String(sheet.columnWidths[String(index)]||110):String(sheet.rowHeights[String(index)]||28));if(size&&Number(size)>15)change(x=>{const s=x.sheets.find(a=>a.id===x.activeSheetId)!;(axis==="c"?s.columnWidths:s.rowHeights)[String(index)]=Number(size)})};
if(!loaded)return <div className="loading">Korczak Nexa<br/><small>Carregando...</small></div>;
const selected=(k:string)=>selectedKeys.includes(k);
return <div className="nexa" tabIndex={0} onKeyDown={onKey}><header><div className="brand"><b>N</b><strong>Korczak Nexa</strong><input value={w.name} onChange={e=>setW({...w,name:e.target.value})}/></div><div className="actions"><button onClick={newWorkbook}>Novo</button><button onClick={()=>setShowDocs(true)}>Abrir</button><button onClick={undoIt} disabled={!undo.length}>↶</button><button onClick={redoIt} disabled={!redo.length}>↷</button><button onClick={()=>void save()}>Salvar</button><label className="import">Importar CSV<input type="file" accept=".csv,text/csv" onChange={e=>{const f=e.target.files?.[0];if(f)importCsv(f)}}/></label><button onClick={exportCsv}>Exportar CSV</button><span>{status}</span></div></header>
<nav><button onClick={()=>setShowDocs(true)}>Arquivo</button><button>Início</button><button>Inserir</button><button>Dados</button><button>Exibir</button><button onClick={()=>toggle("bold")} className={sheet.cells[active]?.style?.bold?"on":""}><b>B</b></button><button onClick={()=>toggle("italic")} className={sheet.cells[active]?.style?.italic?"on":""}><i>I</i></button><button onClick={()=>toggle("underline")} className={sheet.cells[active]?.style?.underline?"on":""}><u>U</u></button><button onClick={()=>toggle("strike")} className={sheet.cells[active]?.style?.strike?"on":""}><s>S</s></button><button onClick={()=>style("align","left")}>⇤</button><button onClick={()=>style("align","center")}>≡</button><button onClick={()=>style("align","right")}>⇥</button><select value={sheet.cells[active]?.style?.numberFormat||"general"} onChange={e=>style("numberFormat",e.target.value as NumberFormat)}><option value="general">Geral</option><option value="number">Número</option><option value="currency">Moeda (R$)</option><option value="percent">Porcentagem</option></select><button onClick={addSheet}>＋ Planilha</button><label>Zoom <input type="range" min="50" max="200" value={zoom} onChange={e=>setZoom(+e.target.value)}/>{zoom}%</label></nav>
<div className="formula"><strong>{selection.start}{selection.end!==selection.start?" : "+selection.end:""}</strong>{editing?<input ref={editRef} value={editValue} onChange={e=>setEditValue(e.target.value)} onBlur={commitEdit} onKeyDown={onKey}/>:<input value={formula} onChange={e=>{setFormula(e.target.value);setEditValue(e.target.value)}} onKeyDown={e=>e.key==="Enter"&&(e.preventDefault(),beginEdit(formula))} placeholder="Valor ou fórmula"/>}<button onClick={()=>{if(editing)commitEdit();else{setEditValue(formula);setEditing(true)}}}>✓</button></div>
<div className="viewport"><div className="grid" style={{transform:`scale(${zoom/100})`,transformOrigin:"top left"}}><div className="corner"/>{Array.from({length:COLS},(_,c)=><div className="head" key={"c"+c} onDoubleClick={()=>resize("c",c)}>{String.fromCharCode(65+c)}</div>)}{Array.from({length:ROWS},(_,r)=><div className="gridrow" key={"row"+r}><div className="row" onDoubleClick={()=>resize("r",r)}>{r+1}</div>{Array.from({length:COLS},(_,c)=>{const k=cellKey(r,c),st=sheet.cells[k]?.style||{};return <div className={"cell "+(selected(k)?"selected ":"")} style={{width:sheet.columnWidths[String(c)]||110,height:sheet.rowHeights[String(r)]||28,fontWeight:st.bold?"700":"400",fontStyle:st.italic?"italic":"normal",textDecoration:[st.underline?"underline":"",st.strike?"line-through":""].filter(Boolean).join(" "),textAlign:st.align||"left"}} key={k} onMouseDown={(e:MouseEvent)=>{drag.current=true;setSelection({start:k,end:k});e.preventDefault()}} onMouseEnter={()=>drag.current&&setSelection(s=>({...s,end:k}))} onMouseUp={()=>{drag.current=false}} onDoubleClick={()=>beginEdit(sheet.cells[k]?.input||"")}>{editing&&active===k?<input className="cellEditor" autoFocus value={editValue} onChange={e=>setEditValue(e.target.value)} onKeyDown={onKey} onBlur={commitEdit}/>:rendered(k)}</div>})}</div>)}</div></div>
<footer>{w.sheets.map(s=><button className={s.id===sheet.id?"active":""} key={s.id} onClick={()=>setW({...w,activeSheetId:s.id})}>{s.name}</button>)}</footer>{showDocs&&<div className="modal"><div className="dialog"><div className="dialogHead"><strong>Planilhas</strong><button onClick={()=>setShowDocs(false)}>×</button></div><button className="newDoc" onClick={()=>{newWorkbook();setShowDocs(false)}}>＋ Nova planilha</button>{documents.length?documents.map(d=><button className="doc" key={d._id||d.name} onClick={()=>openDoc(d)}><strong>{d.name}</strong><small>{new Date(d.updatedAt).toLocaleString("pt-BR")}</small></button>):<p>Nenhuma planilha salva ainda.</p>}</div></div>}</div>}
