import{useEffect,useMemo,useState}from"react";
import type{Workbook}from"@kz-nexa/shared";
type Tab="visual"|"dados"|"colaboracao"|"historico"|"modelos";
type Props={api:string;authToken:string;userEmail:string;workbook:Workbook;sheetId:string;selection:{start:string;end:string};onClose:()=>void};
const parse=(k:string)=>{const m=/^([A-Z]+)(\d+)$/i.exec(k);if(!m)throw Error("Célula inválida");let c=0;for(const ch of m[1].toUpperCase())c=c*26+ch.charCodeAt(0)-64;return{r:+m[2]-1,c:c-1}};
const col=(n:number)=>{let s="";n++;while(n){s=String.fromCharCode(65+(n-1)%26)+s;n=Math.floor((n-1)/26)}return s};
const cells=(w:Workbook,sid:string,range:string)=>{const s=w.sheets.find(x=>x.id===sid)||w.sheets[0],parts=range.split(":"),a=parse(parts[0]),b=parse(parts[1]||parts[0]);const out:string[][]=[];for(let r=Math.min(a.r,b.r);r<=Math.max(a.r,b.r);r++){const row:string[]=[];for(let c=Math.min(a.c,b.c);c<=Math.max(a.c,b.c);c++)row.push(s.cells[col(c)+(r+1)]?.input||"");out.push(row)}return out};
export function Phase2Panel(p:Props){const[tab,setTab]=useState<Tab>("visual"),[charts,setCharts]=useState<any[]>([]),[dashboards,setDashboards]=useState<any[]>([]),[tables,setTables]=useState<any[]>([]),[pivots,setPivots]=useState<any[]>([]),[comments,setComments]=useState<any[]>([]),[shares,setShares]=useState<any[]>([]),[versions,setVersions]=useState<any[]>([]),[templates,setTemplates]=useState<any[]>([]),[message,setMessage]=useState(""),[chartType,setChartType]=useState("bar"),[chartTitle,setChartTitle]=useState("Novo gráfico"),[shareEmail,setShareEmail]=useState(""),[sharePermission,setSharePermission]=useState("viewer"),[comment,setComment]=useState(""),[rowField,setRowField]=useState(""),[valueField,setValueField]=useState(""),[pivotAgg,setPivotAgg]=useState("sum"),[filter,setFilter]=useState(""),[analysis,setAnalysis]=useState<any>(null);
const req=async(path:string,init:RequestInit={})=>{const h=new Headers(init.headers);h.set("Authorization","Bearer "+p.authToken);if(init.body)h.set("content-type","application/json");const r=await fetch(p.api+path,{...init,headers:h});if(!r.ok)throw Error((await r.text()).slice(0,200)||"Falha");return r.status===204?null:r.json()};
const range=p.selection.start+(p.selection.end!==p.selection.start?":"+p.selection.end:"");
const data=useMemo(()=>cells(p.workbook,p.sheetId,range),[p.workbook,p.sheetId,range]);
const reload=async()=>{try{const id=p.workbook._id;if(!id)return;const [a,b,c,d,e,f,g,h]=await Promise.all([req(`/v1/workbooks/${id}/charts`),req(`/v1/workbooks/${id}/dashboards`),req(`/v1/workbooks/${id}/tables`),req(`/v1/workbooks/${id}/pivots`),req(`/v1/workbooks/${id}/comments`),req(`/v1/workbooks/${id}/shares`),req(`/v1/workbooks/${id}/versions`),req("/v1/templates")]);setCharts(a);setDashboards(b);setTables(c);setPivots(d);setComments(e);setShares(f);setVersions(g);setTemplates(h)}catch(x){setMessage(x instanceof Error?x.message:"Falha ao carregar")}};
useEffect(()=>{void reload()},[p.workbook._id]);
const createChart=async()=>{try{await req(`/v1/workbooks/${p.workbook._id}/charts`,{method:"POST",body:JSON.stringify({sheetId:p.sheetId,title:chartTitle,type:chartType,range,position:{x:0,y:0,width:560,height:320}})});setMessage("Gráfico criado.");void reload()}catch(x){setMessage(x instanceof Error?x.message:"Falha")}};
const createTable=async()=>{try{await req(`/v1/workbooks/${p.workbook._id}/tables`,{method:"POST",body:JSON.stringify({sheetId:p.sheetId,name:"Tabela "+(tables.length+1),range,headerRow:true})});setMessage("Tabela criada.");void reload()}catch(x){setMessage(x instanceof Error?x.message:"Falha")}};
const createPivot=async()=>{try{await req(`/v1/workbooks/${p.workbook._id}/pivots`,{method:"POST",body:JSON.stringify({sheetId:p.sheetId,name:"Tabela dinâmica",sourceRange:range,rowField,valueField,aggregation:pivotAgg})});setMessage("Tabela dinâmica criada.");void reload()}catch(x){setMessage(x instanceof Error?x.message:"Falha")}};
const runAnalysis=async()=>{try{const filters=filter?[{column:filter.split("=")[0],operator:"eq",value:filter.split("=")[1]||""}]:[];setAnalysis(await req(`/v1/workbooks/${p.workbook._id}/analysis`,{method:"POST",body:JSON.stringify({sheetId:p.sheetId,range,filters,limit:1000})}));setMessage("Análise concluída.")}catch(x){setMessage(x instanceof Error?x.message:"Falha")}};
const share=async()=>{try{await req(`/v1/workbooks/${p.workbook._id}/shares`,{method:"POST",body:JSON.stringify({email:shareEmail,permission:sharePermission})});setShareEmail("");setMessage("Compartilhamento atualizado.");void reload()}catch(x){setMessage(x instanceof Error?x.message:"Falha")}};
const addComment=async()=>{try{await req(`/v1/workbooks/${p.workbook._id}/comments`,{method:"POST",body:JSON.stringify({sheetId:p.sheetId,cell:p.selection.start,body:comment})});setComment("");setMessage("Comentário adicionado.");void reload()}catch(x){setMessage(x instanceof Error?x.message:"Falha")}};
const createDashboard=async()=>{try{await req(`/v1/workbooks/${p.workbook._id}/dashboards`,{method:"POST",body:JSON.stringify({name:"Dashboard "+(dashboards.length+1),charts:charts.map(x=>x._id),tables:tables.map(x=>x._id),refreshMs:30000})});setMessage("Dashboard criado.");void reload()}catch(x){setMessage(x instanceof Error?x.message:"Falha")}};
const restore=async(v:any)=>{try{await req(`/v1/workbooks/${p.workbook._id}/versions/${v._id}/restore`,{method:"POST"});setMessage("Versão restaurada. Reabra a planilha para carregar o estado restaurado.")}catch(x){setMessage(x instanceof Error?x.message:"Falha")}};
const resolveComment=async(cmt:any)=>{try{await req(`/v1/workbooks/${p.workbook._id}/comments/${cmt._id}`,{method:"PATCH",body:JSON.stringify({resolved:!cmt.resolved})});void reload()}catch(x){setMessage(x instanceof Error?x.message:"Falha")}};
const version=async()=>{try{await req(`/v1/workbooks/${p.workbook._id}/versions`,{method:"POST",body:JSON.stringify({label:"Versão manual",source:"manual"})});setMessage("Versão registrada.");void reload()}catch(x){setMessage(x instanceof Error?x.message:"Falha")}};
const chartSvg=(ch:any)=>{const rows=cells(p.workbook,ch.sheetId,ch.range).slice(1).map(r=>Number(String(r[1]??"").replace(",","."))).filter(Number.isFinite);const max=Math.max(1,...rows),w=520,h=250;return <svg viewBox={`0 0 ${w} ${h}`} role="img" aria-label={ch.title} className="phase2Chart">{rows.map((v,i)=>{const bw=Math.max(4,(w-40)/Math.max(1,rows.length)-6),bh=v/max*190;return ch.type==="line"?<line key={i} x1={20+i*(bw+6)+bw/2} y1={220-(i?rows[i-1]/max*190:bh)} x2={20+i*(bw+6)+bw/2} y2={220-bh} stroke="currentColor" strokeWidth="3"/>:<rect key={i} x={20+i*(bw+6)} y={220-bh} width={bw} height={bh} rx="3" fill="currentColor"/>})}<line x1="15" y1="220" x2="510" y2="220" stroke="currentColor"/></svg>};
return <div className="phase2Overlay"><section className="phase2Panel" role="dialog" aria-modal="true" aria-label="Nexa Completo"><header><div><b>Nexa Completo</b><small>Fase 2 · ferramentas profissionais</small></div><button onClick={p.onClose} aria-label="Fechar">×</button></header><nav className="phase2Tabs">{(["visual","dados","colaboracao","historico","modelos"] as Tab[]).map(t=><button className={tab===t?"active":""} key={t} onClick={()=>setTab(t)}>{t==="visual"?"Visual":t==="dados"?"Dados":t==="colaboracao"?"Colaboração":t==="historico"?"Histórico":"Modelos"}</button>)}</nav>{message&&<div className="phase2Message" role="status">{message}</div>}
{tab==="visual"&&<div className="phase2Content"><div className="phase2Card"><h3>Gráficos</h3><div className="row"><input value={chartTitle} onChange={e=>setChartTitle(e.target.value)} placeholder="Título"/><select value={chartType} onChange={e=>setChartType(e.target.value)}><option value="bar">Colunas</option><option value="line">Linha</option><option value="area">Área</option><option value="pie">Pizza</option><option value="scatter">Dispersão</option></select><button onClick={createChart}>Criar gráfico da seleção</button></div>{charts.map(ch=><article className="phase2ChartCard" key={ch._id}><strong>{ch.title}</strong>{chartSvg(ch)}</article>)}</div><div className="phase2Card"><h3>Dashboards</h3><button onClick={createDashboard}>Criar dashboard com os recursos atuais</button>{dashboards.map(d=><div className="phase2List" key={d._id}>{d.name} · {d.charts.length} gráficos · {d.tables.length} tabelas</div>)}</div></div>}
{tab==="dados"&&<div className="phase2Content"><div className="phase2Card"><h3>Tabela estruturada</h3><p>Seleção atual: <b>{range}</b></p><button onClick={createTable}>Transformar seleção em tabela</button>{tables.map(t=><div className="phase2List" key={t._id}>{t.name} · {t.range}</div>)}</div><div className="phase2Card"><h3>Tabela dinâmica e análise</h3><div className="row"><input value={rowField} onChange={e=>setRowField(e.target.value)} placeholder="Campo de linha (nome do cabeçalho)"/><input value={valueField} onChange={e=>setValueField(e.target.value)} placeholder="Campo de valor"/><select value={pivotAgg} onChange={e=>setPivotAgg(e.target.value)}><option value="sum">Soma</option><option value="count">Contagem</option><option value="average">Média</option><option value="min">Mínimo</option><option value="max">Máximo</option></select><button onClick={createPivot}>Criar</button></div><div className="row"><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Filtro: Coluna=valor"/><button onClick={runAnalysis}>Filtrar/analisar</button></div>{analysis&&<pre className="phase2Result">{JSON.stringify(analysis,null,2)}</pre>}{pivots.map(v=><div className="phase2List" key={v._id}>{v.name} · {v.aggregation}</div>)}</div></div>}
{tab==="colaboracao"&&<div className="phase2Content"><div className="phase2Card"><h3>Compartilhamento e permissões</h3><div className="row"><input type="email" value={shareEmail} onChange={e=>setShareEmail(e.target.value)} placeholder="email@exemplo.com"/><select value={sharePermission} onChange={e=>setSharePermission(e.target.value)}><option value="viewer">Visualizador</option><option value="commenter">Comentador</option><option value="editor">Editor</option></select><button onClick={share}>Compartilhar</button></div>{shares.map(s=><div className="phase2List" key={s._id}>{s.email} · {s.permission}</div>)}</div><div className="phase2Card"><h3>Comentários</h3><div className="row"><input value={comment} onChange={e=>setComment(e.target.value)} placeholder={`Comentário em ${p.selection.start}`}/><button onClick={addComment}>Adicionar</button></div>{comments.map(c=><div className="phase2List" key={c._id}><span><b>{c.cell}</b> · {c.body} · {c.resolved?"resolvido":"aberto"}</span><button onClick={()=>resolveComment(c)}>{c.resolved?"Reabrir":"Resolver"}</button></div>)}</div></div>}
{tab==="historico"&&<div className="phase2Content"><div className="phase2Card"><h3>Versões</h3><button onClick={version}>Criar versão agora</button>{versions.map(v=><div className="phase2List" key={v._id}><span>v{v.version} · {v.label} · {new Date(v.createdAt).toLocaleString("pt-BR")}</span><button onClick={()=>restore(v)}>Restaurar</button></div>)}</div></div>}
{tab==="modelos"&&<div className="phase2Content"><div className="phase2Card"><h3>Templates</h3>{templates.map(t=><div className="phase2List" key={t.id}><b>{t.name}</b><span>{t.category} · {t.description}</span></div>)}</div></div>}</section></div>}
