import{expandRange}from"./spreadsheet.js";
type Getter=(sheet:string|undefined,key:string)=>unknown;
const A1=/^[A-Z]+[1-9][0-9]*$/i;
function scalar(v:unknown):number{if(typeof v==="number")return Number.isFinite(v)?v:0;if(typeof v==="string"&&v.trim()!==""){const n=Number(v.replace(",","."));return Number.isFinite(n)?n:0}return 0}
function sheetName(raw:string|undefined){return raw?.startsWith("'")?raw.slice(1,-1).replaceAll("''","'"):raw}
function splitRef(raw:string):{sheet?:string,key:string}|null{const m=raw.match(/^(?:(?:'((?:[^']|'')+)'|([A-Za-z0-9_ .-]+))!)?([A-Za-z]+[1-9][0-9]*)$/);if(!m||!A1.test(m[3]))return null;return{sheet:sheetName(m[1]||m[2]),key:m[3].toUpperCase()}}
function argsToNumbers(args:string[],get:Getter,sheet:string|undefined):number[]{return args.flatMap(a=>{const t=a.trim();const rm=t.match(/^(?:(?:'((?:[^']|'')+)'|([A-Za-z0-9_ .-]+))!)?([A-Z]+[1-9][0-9]*):(?:(?:'((?:[^']|'')+)'|([A-Za-z0-9_ .-]+))!)?([A-Z]+[1-9][0-9]*)$/i);if(rm){const sh=sheetName(rm[1]||rm[2]||rm[4]||rm[5])||sheet;return expandRange(rm[3],rm[6]).map(k=>scalar(get(sh,k)))}const ref=splitRef(t);if(ref)return[scalar(get(ref.sheet||sheet,ref.key))];const n=Number(t);return Number.isFinite(n)?[n]:[]})}
function tokenize(expr:string):string[]{const out:string[]=[];let i=0;while(i<expr.length){if(/\s/.test(expr[i])){i++;continue}if("(),+-*/%^:!".includes(expr[i])){out.push(expr[i++]);continue}if(expr[i]==="'"){let j=i+1;while(j<expr.length){if(expr[j]==="'"&&expr[j+1]==="'"){j+=2;continue}if(expr[j]==="'")break;j++}if(j>=expr.length)throw new Error("Aspas inválidas");j++;if(expr[j]==="!")j++;while(j<expr.length&&/[A-Za-z0-9$]/.test(expr[j]))j++;out.push(expr.slice(i,j));i=j;continue}let j=i;while(j<expr.length&&/[A-Za-z0-9_.$ !:-]/.test(expr[j]))j++;if(j===i)throw new Error("Token inválido");out.push(expr.slice(i,j).trim());i=j}return out}
export function evaluateFormula(input:string,get:Getter,currentSheet?:string):{value:unknown}{try{if(!input.startsWith("="))return{value:input};const tokens=tokenize(input.slice(1));let p=0;
const parseExpr=():number=>{let v=parseTerm();while(tokens[p]==="+"||tokens[p]==="-"){const op=tokens[p++];const n=parseTerm();v=op==="+"?v+n:v-n}return v};
const parseTerm=():number=>{let v=parsePower();while(tokens[p]==="*"||tokens[p]==="/"){const op=tokens[p++];const n=parsePower();if(op==="/"&&n===0)throw new Error("DIV/0");v=op==="*"?v*n:v/n}return v};
const parsePower=():number=>{let v=parseUnary();if(tokens[p]==="^"){p++;v=Math.pow(v,parsePower())}return v};
const parseUnary=():number=>{if(tokens[p]==="+"){p++;return parseUnary()}if(tokens[p]==="-"){p++;return-parseUnary()}return parsePrimary()};
const parsePrimary=():number=>{const t=tokens[p++];if(t===undefined)throw new Error("Expressão incompleta");if(t==="("){const v=parseExpr();if(tokens[p++]!==")")throw new Error("Parêntese");return v}if(/^[0-9]+(?:\.[0-9]+)?$/.test(t))return Number(t);const fn=t.toUpperCase();if(["SUM","AVERAGE","MIN","MAX","COUNT"].includes(fn)&&tokens[p]==="("){p++;const args:string[]=[];let depth=0,start=p;while(p<tokens.length){if(tokens[p]==="(")depth++;if(tokens[p]===")"){if(depth===0){args.push(tokens.slice(start,p).join(""));p++;break}depth--}if(tokens[p]===","&&depth===0){args.push(tokens.slice(start,p).join(""));start=p+1}p++}const nums=argsToNumbers(args,get,currentSheet);if(fn==="SUM")return nums.reduce((a,b)=>a+b,0);if(fn==="AVERAGE")return nums.length?nums.reduce((a,b)=>a+b,0)/nums.length:0;if(fn==="MIN")return nums.length?Math.min(...nums):0;if(fn==="MAX")return nums.length?Math.max(...nums):0;return nums.length};const ref=splitRef(t);if(!ref)throw new Error("Referência inválida");return scalar(get(ref.sheet||currentSheet,ref.key))};
const value=parseExpr();if(p!==tokens.length)throw new Error("Expressão inválida");return{value:Number.isFinite(value)?value:"#ERROR!"}}catch{return{value:"#ERROR!"}}}
export function displayCell(input:string,get:Getter,currentSheet?:string,format?:(value:unknown)=>string):string{if(!input.startsWith("="))return input;const v=evaluateFormula(input,get,currentSheet).value;return format?format(v):String(v)}
