import{expandRange}from"./spreadsheet.js";
export type Getter=(sheet:string|undefined,key:string)=>unknown;
const A1=/^[A-Z]+[1-9][0-9]*$/i;
function scalar(v:unknown){if(typeof v==="number")return Number.isFinite(v)?v:0;if(typeof v==="string"&&v.trim()!==""){const n=Number(v.replace(",","."));return Number.isFinite(n)?n:0}return 0}
function sheetName(raw:string|undefined){return raw?.startsWith("'")?raw.slice(1,-1).replaceAll("''","'"):raw}
function splitRef(raw:string){const m=raw.match(/^(?:(?:'((?:[^']|'')+)'|([A-Za-z0-9_ .-]+))!)?([A-Za-z]+[1-9][0-9]*)$/);if(!m||!A1.test(m[3]))return null;return{sheet:sheetName(m[1]||m[2]),key:m[3].toUpperCase()}}
function rangeRefs(raw:string,currentSheet:string|undefined){const m=raw.match(/^(?:(?:'((?:[^']|'')+)'|([A-Za-z0-9_ .-]+))!)?([A-Z]+[1-9][0-9]*):(?:(?:'((?:[^']|'')+)'|([A-Za-z0-9_ .-]+))!)?([A-Z]+[1-9][0-9]*)$/i);if(!m)return null;const sh=sheetName(m[1]||m[2]||m[4]||m[5])||currentSheet;return{sheet:sh,keys:expandRange(m[3],m[6])}}
function tokenize(expr:string){const out:string[]=[];let i=0;const ops="(),+-*/%^";while(i<expr.length){if(/\s/.test(expr[i])){i++;continue}if(ops.includes(expr[i])){out.push(expr[i++]);continue}if(expr[i]==="'"){let j=i+1;while(j<expr.length){if(expr[j]==="'"&&expr[j+1]==="'"){j+=2;continue}if(expr[j]==="'")break;j++}if(j>=expr.length)throw Error("Aspas inválidas");j++;if(expr[j]==="!")j++;while(j<expr.length&&/[A-Za-z0-9$]/.test(expr[j]))j++;out.push(expr.slice(i,j));i=j;continue}let j=i;while(j<expr.length&&!/\s/.test(expr[j])&&!ops.includes(expr[j]))j++;if(j===i)throw Error("Token inválido");out.push(expr.slice(i,j));i=j}return out}
export function evaluateFormula(input:string,get:Getter,currentSheet?:string,stack=new Set<string>()):{value:unknown}{try{if(!input.startsWith("="))return{value:input};const id=(sh:string|undefined,k:string)=>String(sh||currentSheet||"")+"!"+k.toUpperCase();const resolve=(sh:string|undefined,k:string):number=>{const key=id(sh,k);if(stack.has(key))throw Error("CIRCULAR");const raw=get(sh,k);if(typeof raw==="string"&&raw.startsWith("=")){const next=new Set(stack);next.add(key);const v=evaluateFormula(raw,get,sh,next).value;if(typeof v==="string"&&v.startsWith("#"))throw Error(v);return scalar(v)}return scalar(raw)};
const resolveRaw=(v:unknown,sh:string|undefined)=>{if(typeof v!=="string"||!v.startsWith("="))return v;const r=evaluateFormula(v,get,sh,stack).value;if(typeof r==="string"&&r.startsWith("#"))throw Error(r);return r};
const valuesForArg=(arg:string):unknown[]=>{const t=arg.trim(),rr=rangeRefs(t,currentSheet);if(rr)return rr.keys.map(k=>resolveRaw(get(rr.sheet,k),rr.sheet));const ref=splitRef(t);if(ref)return[resolve(ref.sheet||currentSheet,ref.key)];return[t]};
const numericValues=(args:string[])=>args.flatMap(a=>valuesForArg(a).map(scalar).filter(Number.isFinite));
const countValues=(args:string[])=>args.flatMap(a=>valuesForArg(a)).filter(v=>typeof v==="number"||typeof v==="string"&&v.trim()!==""&&Number.isFinite(Number(v.replace(",","."))));
const tokens=tokenize(input.slice(1));let p=0;
const parseExpr=():number=>{let v=parseTerm();while(tokens[p]==="+"||tokens[p]==="-"){const op=tokens[p++],n=parseTerm();v=op==="+"?v+n:v-n}return v};
const parseTerm=():number=>{let v=parsePower();while(tokens[p]==="*"||tokens[p]==="/"){const op=tokens[p++],n=parsePower();if(op==="/"&&n===0)throw Error("DIV/0");v=op==="*"?v*n:v/n}return v};
const parsePower=():number=>{let v=parseUnary();if(tokens[p]==="^"){p++;v=Math.pow(v,parsePower())}return v};
const parseUnary=():number=>{if(tokens[p]==="+"){p++;return parseUnary()}if(tokens[p]==="-"){p++;return-parseUnary()}return parsePrimary()};
const parsePrimary=():number=>{const t=tokens[p++];if(t===undefined)throw Error("incompleta");if(t==="("){const v=parseExpr();if(tokens[p++]!==")")throw Error("parêntese");return v}if(/^[0-9]+(?:[.,][0-9]+)?$/.test(t))return Number(t.replace(",","."));const fn=t.toUpperCase();if(["SUM","AVERAGE","MIN","MAX","COUNT"].includes(fn)&&tokens[p]==="("){p++;const args:string[]=[];let depth=0,start=p;while(p<tokens.length){if(tokens[p]==="(")depth++;else if(tokens[p]===")"){if(depth===0){if(p>start)args.push(tokens.slice(start,p).join(""));p++;break}depth--}else if(tokens[p]===","&&depth===0){args.push(tokens.slice(start,p).join(""));start=p+1}p++}if(fn==="COUNT")return countValues(args).length;const nums=numericValues(args);if(fn==="SUM")return nums.reduce((a,b)=>a+b,0);if(fn==="AVERAGE")return nums.length?nums.reduce((a,b)=>a+b,0)/nums.length:0;if(fn==="MIN")return nums.length?Math.min(...nums):0;return nums.length?Math.max(...nums):0}const ref=splitRef(t);if(!ref)throw Error("referência");return resolve(ref.sheet||currentSheet,ref.key)};
const value=parseExpr();if(p!==tokens.length)throw Error("expressão");return{value:Number.isFinite(value)?value:"#ERROR!"}}catch(e){return{value:e instanceof Error&&(e.message==="CIRCULAR"||e.message==="#CIRC!")?"#CIRC!":"#ERROR!"}}}
export function displayCell(input:string,get:Getter,currentSheet?:string,format?:(value:unknown)=>string){if(!input.startsWith("="))return input;const v=evaluateFormula(input,get,currentSheet).value;return format?format(v):String(v)}
