export type NumberFormat="general"|"number"|"currency"|"percent"|"date"|"time";
export type HorizontalAlign="left"|"center"|"right";
export interface CellStyle{bold?:boolean;italic?:boolean;underline?:boolean;strike?:boolean;align?:HorizontalAlign;numberFormat?:NumberFormat;fontSize?:number;fontFamily?:string;fontColor?:string;backgroundColor?:string;wrap?:boolean}
export interface Cell{input:string;style?:CellStyle}
export interface Sheet{id:string;name:string;cells:Record<string,Cell>;columnWidths:Record<string,number>;rowHeights:Record<string,number>;frozenRows:number;frozenColumns:number;hiddenRows?:Record<string,boolean>;hiddenColumns?:Record<string,boolean>;mergedRanges?:string[]}
export interface Workbook{_id?:string;ownerId:string;name:string;schemaVersion:number;sheets:Sheet[];activeSheetId:string;createdAt:string;updatedAt:string}
export function columnName(index:number){let n=index+1,s="";while(n){const r=(n-1)%26;s=String.fromCharCode(65+r)+s;n=Math.floor((n-1)/26)}return s}
export function columnIndex(name:string){let n=0;for(const c of name.toUpperCase()){if(c<"A"||c>"Z")throw new Error("Coluna inválida");n=n*26+c.charCodeAt(0)-64}return n-1}
export function cellKey(row:number,col:number){if(row<0||col<0)throw new Error("Coordenada inválida");return columnName(col)+(row+1)}
export function parseCellKey(key:string){const m=/^([A-Z]+)([1-9][0-9]*)$/i.exec(key.trim());if(!m)throw new Error("Célula inválida");return{col:columnIndex(m[1]),row:Number(m[2])-1}}
export function expandRange(a:string,b:string){const p=parseCellKey(a),q=parseCellKey(b),out:string[]=[];for(let r=Math.min(p.row,q.row);r<=Math.max(p.row,q.row);r++)for(let c=Math.min(p.col,q.col);c<=Math.max(p.col,q.col);c++)out.push(cellKey(r,c));return out}
export function formatNumber(value:unknown,format:NumberFormat="general"){if(typeof value!=="number"||!Number.isFinite(value))return String(value??"");if(format==="currency")return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(value);if(format==="percent")return new Intl.NumberFormat("pt-BR",{style:"percent",maximumFractionDigits:2}).format(value);if(format==="number")return new Intl.NumberFormat("pt-BR",{maximumFractionDigits:10}).format(value);if(format==="date")return new Intl.DateTimeFormat("pt-BR").format(new Date(value));if(format==="time")return new Intl.DateTimeFormat("pt-BR",{hour:"2-digit",minute:"2-digit",second:"2-digit"}).format(new Date(value));return String(value)}
export function csvEscape(value:string){return /[",\n\r]/.test(value)?'"'+value.replaceAll('"','""')+'"':value}
export function parseDelimited(text:string,delimiter=","){const rows:string[][]=[];let row:string[]=[],field="",quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(quoted){if(ch==='"'){if(text[i+1]==='"'){field+='"';i++}else quoted=false}else field+=ch}else if(ch==='"'&&field===""){quoted=true}else if(ch===delimiter){row.push(field);field=""}else if(ch==="\n"){row.push(field);rows.push(row);row=[];field=""}else if(ch==="\r"){if(text[i+1]==="\n")i++;row.push(field);rows.push(row);row=[];field=""}else field+=ch}if(field!==""||row.length)row.push(field);if(row.length)rows.push(row);return rows}
export const parseCsv=(text:string)=>parseDelimited(text,",");
export function toDelimited(rows:string[][],delimiter=","){return rows.map(r=>r.map(csvEscape).join(delimiter)).join("\n")}
export function shiftCellKey(key:string,rowDelta:number,colDelta:number){const p=parseCellKey(key);return cellKey(p.row+rowDelta,p.col+colDelta)}
export function shiftFormulaReferences(formula:string,rowDelta:number,colDelta:number){if(!formula.startsWith("="))return formula;return formula.replace(/((?:'[^']*(?:''[^']*)*'|[A-Za-z0-9_ .-]+)!)?\$?([A-Z]+)\$?([1-9][0-9]*)/g,(m,sh,col,row)=>{const absCol=m.includes("$"+col),absRow=m.includes("$"+row);const c=columnIndex(col)+(absCol?0:colDelta),r=Number(row)-1+(absRow?0:rowDelta);if(c<0||r<0)return m;return (sh||"")+(absCol?"$":"")+columnName(c)+(absRow?"$":"")+(absRow?String(r+1):String(r+1))})}
